# docker-compose.yml
version: '3'
services:
  composer:
    image: composer:1.9.3
    command: install
    environment:
      - COMPOSER_CACHE_DIR=/app/.cache/composer
    volumes:
      - ./:/app
    restart: 'no'
  php:
    image: php:7.4-cli
    restart: 'no'
    volumes:
      - ./:/app
    working_dir: /app
  phpunit:
    image: php:7.4-cli
    restart: 'no'
    volumes:
      - ./:/app
    working_dir: /app
    entrypoint: vendor/bin/phpunit
  fpm:
    image: php:7.4-fpm
    container_name: cart
    restart: always
    volumes:
      - ./:/var/www/html/